### ISSUE TITLE
Permissions bug friends commands

### ISSUE THREAD

**Issue by SylisMC** [Xibalba/ZHorse#111] opened 2019-03-07 21:24 UTC
Im running spigot 1.13 and luckperms, and ive got a bug with permissions where using the permissions nodes zh.friend zh.friend.add zh.friend.list & zh.friend.remove dont actually do anything and users are greated with "you dont have "zh.friend" 

Using zh.friend.* works perfectly fine and with friend.* all friends commands are available. but the individual friend command permissions nodes dont work

**Comment by Zedd7** [comment] 2019-03-08 09:26
That's weird, I'll try to find out what's not working.
Could you check with LuckPerms commands if someone has the zh.friend perm when you only give him this perm and not zh.friend.* ?
Also, is there something particular that you're trying to achieve by not using zh.friend.* or is it just for the sake of testing ?

**Comment by Zedd7** [comment] 2019-03-08 11:57
I just tried giving myself only the `zh.friend` and `zh.friend.list` permissions and it works fine.
As you can seed on this screenshot, the commands `/zh friend add` and `/zh friend remove` don't appear because I don't have the required permission : https://gyazo.com/2464632d684a4d216da2e8bd7b2309a3
I'm using ZHorse 1.8.1 snapshot 2 (pretty much the same as 1.8.0 release), PaperMC 513 and PermissionsBukkit 2.5.

Make sure that your LuckPerms' config respects the file format, don't mix blanks and tabs, etc.
I'm closing the issue as I couldn't reproduce the problem but feel free to give me some updates below ;)

**Closed as completed** 2019-03-08 11:58 UTC
Labels: invalid
