### ISSUE TITLE
zh list eror / bug 1.14.3 ZHorse v1.8.1 snapshot 3

### ISSUE THREAD

**Issue by rybuilder23** [Xibalba/ZHorse#122] opened 2019-07-08 13:33 UTC
### What are you trying to do ?

/zh list

### What is the expected behavior ?

a list of the horse's you have

### What is the actual behavior ?

noting big eror in console

### How to reproduce the bug ?

1. /zh list

### Console output 

https://pastebin.com/USwGCsKt
https://pastebin.com/kFJqcv71

## Environment specifications

- Operating system :

idk server is hosted 

- Java version :

8 i think

08.07 13:24:58 [Server] INFO This server is running Paper version git-Paper-125 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
08.07 13:24:58 [Server] INFO Checking version, please wait...
08.07 13:24:58 [Server] INFO Previous version: git-Paper-124 (MC: 1.14.3)
08.07 13:24:58 [Server] INFO You are running the latest version

- ZHorse version :
ZHorse v1.8.1 snapshot 3

- Database : 
SQLite

**Comment by Zedd7** [comment] 2019-08-11 15:21
Is this still happening with Paper for 1.14.4 ?
And with Spigot 1.14.4 only (no Paper) ?

**Comment by rybuilder23** [comment] 2019-08-12 11:06
With Paper-166 (MC: 1.14.4) i still get the eror.
https://pastebin.com/JpiunsmA
and with lastest spigot i also get the eror
with latest spigot 
https://pastebin.com/uyFzJbh1

**Comment by Zedd7** [comment] 2019-11-24 14:30
I tried to replicate this issue with the latest Spigot and Paper build (as of today) but everything works fine for me on different server configs.
I'm closing this issue since I don't know if it's still happening and, if so, how to reproduce it but feel free to open it again if you have additional details to provide.

**Closed as completed by Zedd7** 2019-11-24 14:30 UTC
