### ISSUE TITLE
Errors in console when trying to respawn a missing horse

### ISSUE THREAD

**Issue by SofieHL** [Xibalba/ZHorse#48] opened 2017-04-19 02:21 UTC
On 1.11.2  version 1.66
Trying to do /zh info, /zh tp. /zh here or any other command has no effect on the target horse if it has the [restricted] tag. Also causes random horses to appear and disappear. The pastbin shows the errors that appear in the console.

https://pastebin.com/SG8wXqVz

**Comment by Zedd7** [comment] 2017-04-19 12:33
Are you using MySQL ?
It could be that your MySQL server is outdated and needs an upgrade, as I am using MySQL57's features in ZHorse 1.6.6.

**Comment by SofieHL** [comment] 2017-04-19 14:30
No I am using SQLite.  
It appears that horses that are spawned pretamed are not registering properly in the database when claimed. They receive the [restricted] tag and trying to execute commands on them spawns a random horse at their location.
If I tame a wild horse, the [protected] and [locked] tags are properly applied and commands function normally on them.

**Comment by Zedd7** [comment] 2017-04-19 15:22
Do you have any error on server startup or /zh reload ?

Btw the Restricted flag simply means that a horse is neither locked nor protected, so it's the same as no flag in 1.6.5

**Comment by SofieHL** [comment] 2017-04-20 01:10
No errors on startup or /zh reload
Further testing has show no issues with new horse spawns on 1.11.2. It only seems to happen to horses that were previously spawned with version 1.6.1 on 1.10.2 with "/zh spawn horse tamed" I cant even remove them from the database with /zh admin.

**Comment by Zedd7** [comment] 2017-04-20 08:23
Does it say that you must claim the horse first when you do /zh info on such horses ?

**Comment by SofieHL** [comment] 2017-04-20 14:13
They disappeared from the world when i upgraded to 1.11.2 and 1.66 but still show up in /zh list. When I do /zh info on them, nothing happens in chat but a random wild un-named horse spawns in their last location and the errors from the pastbin file appear on the console.

**Comment by Zedd7** [comment] 2017-04-20 15:01
Is the error logs of your pastebin complete ? It looks like some part is missing

**Comment by SofieHL** [comment] 2017-04-21 00:00
Here is a new pastebin, I think a console filter was blocking part of it in the other one,

https://pastebin.com/L30uNFVH

**Comment by Zedd7** [comment] 2017-04-21 09:22
I found why the errors were showing up in the console : it's a bug introduced in 1.6.6 (the horse's owner assignation) that occurs when ZHorse spawns a horse and assign its stats from the records in the database. This is however not your main issue, as horses should not have been missing in the first place.

As we are facing two different issues here (missing horses and impossibility to respawn them), I will rename this ticket and close it with the next commit.

Could you then try to reproduce your issue (disappearing horses) by using the snapshot 1 of ZHorse 1.6.7 that I will submit here and open a new ticket describing how to reproduce this issue ?

Please note that as 1.6.7 snapshot 1 fixes the bug preventing horses to be respawned, /zh here -i 1 on a missing horse will not yields errors. The issue that you should track is how to make horse disappear by simply updating the plugin.

**Closed as completed** 2017-04-21 09:36 UTC
Labels: bug

**Comment by Zedd7** [comment] 2017-04-21 09:39
ZHorse 1.6.7 snapshot 1 : http://www.mediafire.com/file/g4ozjg4wee675k8/ZHorse+1.6.7+snapshot+1.jar

**Comment by SofieHL** [comment] 2017-04-22 01:14
The 1.6.7 snapshot fixed all the issues. The missing horses returned when I did /zh info on them.
