### ISSUE TITLE
 /zh list bug

### ISSUE THREAD

**Issue by ghost** [Xibalba/ZHorse#92] opened 2018-07-29 05:59 UTC
# Please be aware that ZHorse developement and maintenance is put on hold for the moment.
# However, this issue page remains open for questions and quick support.
# If your ticket requires modifications of the code, you will have to wait until either me or another developer resumes the project.

### What are you trying to do ? do /zh list

Description of the task to be done goes here.

### What is the expected behavior ?

Description of the expected behavior goes here.

### What is the actual behavior ?

Description of the actual behavior goes here.

### How to reproduce the bug ?

1. Step 1
2. Step 2
3. ...

### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !

## Environment specifications

- Operating system :

- Java version :

- Server version :

- ZHorse version :

- Database :

**Comment by Zedd7** [comment] 2018-07-29 09:27
Duplicate of #93

**Closed as completed** 2018-07-29 09:28 UTC
Labels: duplicate
