### ISSUE TITLE
Console issue and lag

### ISSUE THREAD

**Issue by Strangehadron** [Xibalba/ZHorse#116] opened 2019-04-01 23:28 UTC
### What are you trying to do ?

Nothing spécial, got some lag and console spam every evening on my server since one weeks. Have not done anything special or change anything in the server.
When this happen, the server lag and crash
When i perform a timings at the time of the "error", i see that : https://imgur.com/bp0DRjC

### Console output 

https://pastebin.com/C5GA8ctp

## Environment specifications

- Operating system : linux

- Java version : 8

- Server version : Paper version git-Paper-561 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

- ZHorse version : 1.8.0

- Database : SQLite

Thanks for your help !

**Comment by Zedd7** [comment] 2019-04-02 07:16
Is it the complete stacktrace ? It seems to be missing some part.
Also, are you sure that you updated nothing ? Maybe Java, Paper, Vault or something on your machine ? Can you think of any reason of why it happens in the evening ?

**Comment by Strangehadron** [comment] 2019-04-02 10:06
Nop, i've not change any settings, or add any plugin for a while or even update paper or vault (vault is on the last version since it's out)

Honestly I don't know, I will disable my plugins one by one to see if one of them could led to this.

Here is the screen of the console https://imgur.com/a/D5brjAd and this message repeat two times or three when it appear.
Don't know if the lag is the culprit and led to this or if it's lag because of this. :x

**Comment by Zedd7** [comment] 2019-04-02 21:23
Could you upload the entire log file of a run session of your server ?

**Comment by Strangehadron** [comment] 2019-04-03 14:43
Yup, can i pm you somewhere the entire log ?

**Comment by Zedd7** [comment] 2019-04-03 20:09
Sure, look for 'Z3dd7' on Spigot and you should find me.

**Comment by Strangehadron** [comment] 2019-04-06 15:01
Thanks, just pm you !

**Comment by Zedd7** [comment] 2019-04-07 10:56
I checked your logs and tried to reproduce the issue with both SQLite and MySQL but it worked fine for me, even when forcing the server to load/unload a lot of chunks full of registered horses (which is the context of your issue, at least in the logs you provided).

As it is not a regular crash but instead a freeze of the server's main thread, I opened a topic on Spigot's forum : https://www.spigotmc.org/threads/server-thread-freezing-on-sqlite-querry.367182/

**Comment by Zedd7** [comment] 2019-04-07 18:39
In case you are not following the Spigot's thread, do you use the default and local `plugins/ZHorse/zhorse.db` file as SQLite database ?
Could you also PM me a copy of this file ?

**Comment by Strangehadron** [comment] 2019-04-08 14:46
Hey, I've just red it !
Yes, I use the default SQLite db, I've tried MySQL but it never worked for me (error on creation of tables). Just PM you the file !

**Comment by Zedd7** [comment] 2019-04-11 20:12
Hey, sorry for the delay I was quite busy lately.

So, if your zhorse.db file is located in the same location as your server is, there shouldn't be any reason for those long freezes.
I also thoroughly tested your db on two different servers (one being the closest possible to yours) and I couldn't find anything wrong with the file. I could even export the data to mysql/mariadb and import them back to sqlite without any trouble.

Unfortunately, I have no idea of what is causing those freezes nor can I tell if it comes from ZHorse or your installation. As some Spigot users pointed out ZHorse could be improved, in particular regarding data fetching efficiency, but there is a 1% chance that it would solve your issue.

Thus, I recommend that you try mysql (or mariadb, to your liking) one more time.
All you have to do is :
1. Install and start a mysql/mariadb server
2. Create a database/schema `zhorse`
3. Edit ZHorse's config.yml file to fill the options for mysql (user, password, db name, etc.) and set mysql as your db type.
4. Log in and type `/zh admin import sqlite` which will import your sqlite data into your current database (here mysql).
More details here : https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks#how-to-use-zh-admin-import-

I tag this issue as wontfix but do not hesitate to reply on it if you have updates ;)

**Closed as completed** 2019-04-11 20:13 UTC
Labels: wontfix
