### ISSUE TITLE
Console Spammed Issue

### ISSUE THREAD

**Issue by Fordy436** [Xibalba/ZHorse#53] opened 2017-05-01 14:04 UTC
Switch Config files to MySQL - Following issue spammed:

01.05 10:03:01 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'db_19569.ZHorse_horse' doesn't exist
01.05 10:03:01 [Server] WARN at sun.reflect.GeneratedConstructorAccessor153.newInstance(Unknown Source)
01.05 10:03:01 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01.05 10:03:01 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:387)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
01.05 10:03:01 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
01.05 10:03:01 [Server] WARN at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.hasResult(SQLDatabaseConnector.java:163)
01.05 10:03:01 [Server] WARN at com.gmail.xibalbazedd.zhorse.managers.DataManager.isHorseRegistered(DataManager.java:313)
01.05 10:03:01 [Server] WARN at com.gmail.xibalbazedd.zhorse.utils.ChunkLoad.<init>(ChunkLoad.java:22)
01.05 10:03:01 [Server] WARN at com.gmail.xibalbazedd.zhorse.managers.EventManager.onChunkLoad(EventManager.java:71)
01.05 10:03:01 [Server] WARN at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
01.05 10:03:01 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.05 10:03:01 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
01.05 10:03:01 [Server] WARN at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.05 10:03:01 [Server] WARN at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.Chunk.loadNearby(Chunk.java:910)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:131)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:95)
01.05 10:03:01 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:561)
01.05 10:03:01 [Server] WARN at org.bukkit.Location.getBlock(Location.java:87)
01.05 10:03:01 [Server] WARN at de.epiceric.shopchest.listeners.HologramUpdateListener.updateHolograms(HologramUpdateListener.java:45)
01.05 10:03:01 [Server] WARN at de.epiceric.shopchest.listeners.HologramUpdateListener.onPlayerMove(HologramUpdateListener.java:37)
01.05 10:03:01 [Server] WARN at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
01.05 10:03:01 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.05 10:03:01 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
01.05 10:03:01 [Server] WARN at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.05 10:03:01 [Server] WARN at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
01.05 10:03:01 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
01.05 10:03:01 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
01.05 10:03:01 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
01.05 10:03:01 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
01.05 10:03:01 [Server] WARN at java.lang.Thread.run(Thread.java:745)
01.05 10:03:17 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'db_19569.ZHorse_horse' doesn't exist
01.05 10:03:17 [Server] WARN at sun.reflect.GeneratedConstructorAccessor153.newInstance(Unknown Source)
01.05 10:03:17 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01.05 10:03:17 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:387)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
01.05 10:03:17 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
01.05 10:03:17 [Server] WARN at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.hasResult(SQLDatabaseConnector.java:163)
01.05 10:03:17 [Server] WARN at com.gmail.xibalbazedd.zhorse.managers.DataManager.isHorseRegistered(DataManager.java:313)
01.05 10:03:17 [Server] WARN at com.gmail.xibalbazedd.zhorse.utils.ChunkLoad.<init>(ChunkLoad.java:22)
01.05 10:03:17 [Server] WARN at com.gmail.xibalbazedd.zhorse.managers.EventManager.onChunkLoad(EventManager.java:71)
01.05 10:03:17 [Server] WARN at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
01.05 10:03:17 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.05 10:03:17 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
01.05 10:03:17 [Server] WARN at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.05 10:03:17 [Server] WARN at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.Chunk.loadNearby(Chunk.java:910)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:131)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:95)
01.05 10:03:17 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:561)
01.05 10:03:17 [Server] WARN at org.bukkit.Location.getBlock(Location.java:87)
01.05 10:03:17 [Server] WARN at de.epiceric.shopchest.listeners.HologramUpdateListener.updateHolograms(HologramUpdateListener.java:45)
01.05 10:03:17 [Server] WARN at de.epiceric.shopchest.listeners.HologramUpdateListener.onPlayerMove(HologramUpdateListener.java:37)
01.05 10:03:17 [Server] WARN at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
01.05 10:03:17 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.05 10:03:17 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
01.05 10:03:17 [Server] WARN at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.05 10:03:17 [Server] WARN at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
01.05 10:03:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
01.05 10:03:17 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
01.05 10:03:17 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
01.05 10:03:17 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
01.05 10:03:17 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by Zedd7** [comment] 2017-05-01 14:09
It says that the table "db_19569.ZHorse_horse" doesn't exist.
Here, Zhorse_ seems to be the table prefix. Check that the config option Databases.mysql-config.table-prefix is "ZHorse" (without _ )

**Comment by Fordy436** [comment] 2017-05-06 01:54
database: db_19569
    table-prefix: 'ZHorse'

Is this correct? Should it have the "_"?

**Comment by Zedd7** [comment] 2017-05-06 07:10
It should be correct, as stated by the config comments that I updated accordingly : https://github.com/Xibalba/ZHorse/blob/1.6.7/config.yml#L83

There are two things that you could try : 
1. Switch to SQLite, just to see if the tables get created as expected
2. Make a fresh install of ZHorse (on MySQL) and look for errors in console

**Comment by Fordy436** [comment] 2017-05-07 20:16
I did that... it made the following tables:
ZHorse_horse_stats
ZHorse_inventory_item
ZHorse_player

But not ZHorse_horse

**Comment by Zedd7** [comment] 2017-05-07 20:58
That's really weird.. Maybe is there an error message that you didn't see ? Or the .jar could be corrupted..
I will try to reproduce it. In the meantime, you could create the table yourself : https://raw.githubusercontent.com/Xibalba/ZHorse/master/res/sql/tables/horse-table.sql
Don't forget to replay any occurrence of "prefix_" by "Zhorse_"

**Comment by Zedd7** [comment] 2017-06-07 09:07
I tried to replicate this in many way but the bug you described never happened.
I mark this issue as expired and close it for now. Feel free to reply if you want to re-open it with new infos

**Closed as completed** 2017-06-07 09:07 UTC
Labels: expired
