### ISSUE TITLE
Internal Error!!

### ISSUE THREAD

**Issue by BroganMC** [Xibalba/ZHorse#100] opened 2018-12-02 18:51 UTC
# Please be aware that ZHorse developement and maintenance is put on hold for the moment.
# However, this issue page remains open for questions and quick support.
# If your ticket requires modifications of the code, you will have to wait until either me or another developer resumes the project.

### What are you trying to do ?

Use any zHorse command

### What is the expected behavior ?

Proper behavior happens 

### What is the actual behavior ?

"An internal error occurred..."

### How to reproduce the bug ?

Execute any zhorse command

### Console output 

https://pastebin.com/Bkz1ueRA

## Environment specifications

- Operating system : Windows

- Java version : 8

- Server version : Craftbukkit version git-Spigot-eb3d921-2b93d83

- ZHorse version : 1.7.0

- Database : unknown

Note: Please don't close my issue before you get a response from me! You closed my previous issue and your solution did not even help.

**Comment by Zedd7** [comment] 2018-12-03 09:59
The console still mentions ZHorse 1.7.1 + duplicate of #99

**Closed as completed** 2018-12-03 09:59 UTC
Labels: duplicate, invalid
