### ISSUE TITLE
Can't select a horse properly

### ISSUE THREAD

**Issue by hannahequine** [Xibalba/ZHorse#113] opened 2019-03-23 05:56 UTC
### What are you trying to do ?
Set my horses stable or teleport them to me
### What is the expected behavior ?
Once my horse (Hera) is selected by me riding it (checked their info, said Hera was indeed selected) I should be able to tp them to me once I go elsewhere.
### What is the actual behavior ?
Once my horse Here is selected by me riding her (checked their info, said Hera was indeed selected) I go to my stable and try to do /zh here or /zh stable set and it tps or sets the stable of my OTHER horse, Zeus.
### How to reproduce the bug ?
1. Have two horses
2. /zh here or /zh stable set
### Console output 
Had no console output.
## Environment specifications

- Operating system : Windows

- Java version : ??? should be up to date unsure

- Server version : CraftBukkit version git-Bukkit-2b93d83(MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

- ZHorse version : 1.7.0

- Database :??? should be the default I hadn't messed with anything. I use PermissionsEx and vault if that helps at all. 
EXTRA: would be cool if you added a way to click on your horses name to select them after doing /zh list :)

**Comment by Zedd7** [comment] 2019-03-23 20:26
Hello, there is currently no way to select a horse by riding it or clicking on it (yet). However, this is a feature that I consider adding in the following updates.

To apply commands (like `/zh here` or `/zh stable`) on a horse that is not the first of your list and that you are not currently riding, you must either specify its name (ex: `/zh here Hera`) or its id with the `-i` flag (ex: `/zh here -i 2`). Note that the later is reserved for more advanced use cases, read [the related page on the wiki](https://github.com/Zedd7/ZHorse/wiki/Commands) if you want to learn more on that.
If you plan to use Hera more often than your first horse, you could also consider swapping them in your list with `/zh swap 1 2`.

Hope this helps. Don't be afraid to ask questions below even though I'm closing this ticket as it is not a bug report.

**Closed as completed** 2019-03-23 20:26 UTC
Labels: invalid
