### ISSUE TITLE
Error during spawning a missing horse.

### ISSUE THREAD

**Issue by Rodzynus** [Xibalba/ZHorse#50] opened 2017-04-23 15:15 UTC
This error appears when a player tries to _/zh here_ a horse that's gone missing.
https://pastebin.com/7r3qMCSd

**Comment by Zedd7** [comment] 2017-04-23 22:10
Hey, it has been fixed in 1.6.7 snapshot 1. See below : 

Duplicate of #48

**Closed as completed by Zedd7** 2017-04-23 22:10 UTC
Labels: duplicate
